### PR TITLE
Fix delete and Suppress 'go test' output by default

### PR DESCRIPTION
**Pull request by corsc**
- Removed duplication in Gonerator code
- Refactored cleaner to interface based; added some tests and retested clean flag
- Restored previous functionality of suppressing go test output and added option to output it
- Converted logging code to use custom logger

### CODE REVIEW

**Comment by corsc** [comment]
@lowjoel would you like to review this?

Please note for your IntelliJ integration you will have to use the new `-n=false` flag

**Comment by corsc** [comment]
@harrycmfan This PR is designed to fix the issues we discussed

**Comment by lowjoel** [comment]
Changing the flag from n to q is probably OK, but I'm concerned that the entire `go test` output is buffered in memory. This would delay the feedback that IntelliJ would display when it is running the tests.

Ideally stderr is also real-time, but stdout was more important, from my observations.

**Comment by corsc** [comment]
Ok, I will switch it back to cmd.Run() for noisy mode

**Pull request merged**
